### PR TITLE
Wiggle update 1 7 6

### PR DESCRIPTION
**Pull request by sammyfreg**
**Note**
It seems that the original depot has been quiet for a while, with pull requests left still. So, I decided to pull my update into this updated fork instead.

**Description**
- Pulled changes from this master fork.
- Updated NetImgui to 1.7.6 (comes with data compression for reduced bandwidth)
- Added support for ImUnrealCommand which gives a nice UI to browser/run Unreal commands

### CODE REVIEW

**Comment by WiggleWizard** [comment]
I probably need to get my head stuck into NetImgui too at some point so this branch can be managed a bit better and any changes I make likely need to be compatible with this branch too?

**Comment by sammyfreg** [comment]
Yes, all of your changes are compatibles and in fact, already merged in this branch now.

The only branch difference, is the addition of the NetImgui support with everything else up to date to master. NetImgui doesn't change the basic behavior of the plugin and everything is guarded by the `NETIMGUI_ENABLED` define, so it can easily be found/disabled.

The branch could easily become the master branch, @segross just did not had the time to confirm that everything was stable as it should.

**Comment by WiggleWizard** [comment]
I'd like for NetImgui to be in mainline and not for it to be religated to a branch tbh. The strategy here I think would be to push the current state of the mainline branch into a release, then merge NetImgui into mainline and go from there.

We need to figure out how version naming would work then as from what I can see you have semver'd NetImgui and the mainline UnrealImGui doesn't seem to have a defined version AFAIK. I'll look what we can do about that tonight.

**Comment by sammyfreg** [comment]
The version name seen in the pull request is only a mention of which **NetImgui** version has been integrated. The **UnrealImgui** plugin itself doesn't have a version that's different than the main branch. This **NetImgui branch** already as all the content of the master + NetImgui client code, so pushing the branch to master should be easy and conflicts free, since the merge from master already happened in this PR.

**Comment by WiggleWizard** [comment]
I see, gotcha. The naming is all a little confusing to me because I haven't spent the time investigating NetImgui at all! I'll do a local merge at some point and check out whether the base works (local drawlist rendering) without modifications to project build files. If that works then i'll merge the two branches together into one (and release as v1.1.0) as I'm pretty sure at some point we will want to be checking out NetImGui and it would be nice to just have a simple preprocessor to enable that in our builds when the time comes.

**Comment by sammyfreg** [comment]
NetImgui does not change the Dear ImGui drawing, or how the plugin works. All it does, is intercept the Dear ImGui drawdata and send it to the NetImgui Server, and then process the input received from the server. (mostly, technically it can create a new Dear Imgui Context to handle dual imgui drawing on both local and server).

You can already disable NetImgui by platform/build, by changing the value of `kUseNetImgui` in _NetImguiLibrary.Build.cs_

- **Dear ImGui**: Library to create immediate mode UI
- **NetImgui**: Library I created to easily add remote control to any Dear ImGui codebase. Designed to be non-intrusive.
  - **NetImgui Client**: A few cpp files that adds the remote access to a program using Dear ImGui. This is what's integrated to the UnrealImGui plugin.
  - **NetImgui Server**: An application on which we display and control the Dear ImGui menu of clients connected to it.
- **UnrealImGui**: This plugin, which integrate Dear ImGui to Unreal for some immediate mode UI fun
- **UnrealImgui NetImgui branch**: This plugin with the addition of NetImgui Client code. Works exactly the same except with remote access also possible (but local rendering still works). Doesn't require any change by plugin user and in fact, the code is almost identical to master branch when setting `kUseNetImgui` to false. There is one additional small difference from master branch, which is the addition of 'ImUnrealConsole' to have a UI for Unreal Console Commands. Added that in this PR and it is unrelated to NetImgui, just something else I did.
- **UnrealNetImgui**: Plugin I created to add Dear ImGui support to Unreal, with NetImgui also integrated. Can only draw remotely. Not related to this plugin, but very simple and can help understand the NetImgui integration.

**Pull request merged**
